### ISSUE TITLE
Error compiling - Arguments to path.resolve must be strings

### ISSUE THREAD

**Issue by Zoxive** [cretz/pratphall#19]
```
path.js:313
        throw new TypeError('Arguments to path.resolve must be strings');
              ^
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve [as resolvePath] (path.js:313:15)
    at addUnitAndReferences (/usr/lib/node_modules/pratphall/bin/ppc.js:23777:41)
    at Array.forEach (native)
    at Compiler.compile (/usr/lib/node_modules/pratphall/bin/ppc.js:23806:19)
    at Compiler.run (/usr/lib/node_modules/pratphall/bin/ppc.js:24130:33)
    at CommandLineRunner.run (/usr/lib/node_modules/pratphall/bin/ppc.js:28050:26)
    at Pratphall (/usr/lib/node_modules/pratphall/bin/ppc.js:28058:29)
    at Object.<anonymous> (/usr/lib/node_modules/pratphall/bin/ppc.js:28059:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

I fixed/hacked by changing the following line

/usr/lib/node_modules/pratphall/bin/ppc.js: 23806

```
files.foreach(addUnitAndReferences);

--- TO -> 

files.forEach(function(file, i)
{
    addUnitAndReferences(file);
});

```

Not sure if this is because of a newer version of typescript, or the version of nodejs I have installed.

**Comment by cretz** [comment]
It likely is because of the new version. I've kinda abandoned this project though, or at least haven't worked on it in a while. It might be worth taking that into consideration before using it for anything serious.
